### ISSUE TITLE
Send image attachments cannot be viewed

### ISSUE THREAD

**Issue by pengyanbing84** [mailjet/mailjet-apiv3-python#56] opened 2020-07-24 12:36 UTC
Send the attached image attachment In the html body, the image attachment cannot be displayed in the test received mail

**Comment by andriyy** [comment] 2020-09-18 13:10
Could you give an example how are you sending image attachment?

**Comment by pengyanbing84** [comment] 2020-09-22 04:03
The picture link is embedded in html,

html_mail = """
<td align="center"
                                                                                        class="x_bmeImage"
                                                                                        style="border-collapse:collapse; padding:20px; border-width:50px; border-color:rgb(22,167,224); border-style:solid">
                                                                                        <a href=""
                                                                                           target="_blank"
                                                                                           rel="noopener noreferrer"
                                                                                           data-auth="NotApplicable"><img
                                                                                                data-imagetype="External"
                                                                                                src=""
                                                                                                width="206" alt=""
                                                                                                border="0"
                                                                                                style="max-width:206px; display:block; width:206px"></a>
                                                                                    </td>
""""


Send example:

 data = {
                'Messages': [
                    {
                        "From": {
                            "Email": "",
                            "Name": ""
                        },
                        "To": [
                            {
                                "Email": "{}".format(mail_[1]),
                                "Name": ""
                            }
                        ],
                        "Subject": "",
                        "TextPart": "",
                        "HTMLPart": html_mail

                    }
                ]
            }

**Comment by diskovod** [comment] 2020-09-22 11:50
Hi,
it's not enough to reproduce your problem, we have at least understand how your email body with image link/attached looks like, you can provide it with example data and without any personal/project info and we will take a look. Thanks!

**Comment by diskovod** [comment] 2020-11-03 15:56
No additional information regarding this issue. Can't reproduce. Closing

**Closed by diskovod** 2020-11-03 15:56 UTC
